const mongoose = require("mongoose");
const Badge = require("../models/Badge");
require("dotenv").config();

const badges = [
  // Sharing Badges
  {
    name: "First Share",
    description: "Shared your first item with the community",
    icon: "📦",
    iconComponent: "Package",
    color: "from-green-500 to-emerald-600",
    backgroundColor: "bg-green-100",
    textColor: "text-green-800",
    level: "bronze",
    rarity: "common",
    points: 100,
    requirementType: "items_shared",
    requirementValue: 1,
    category: "sharing",
  },
  {
    name: "Sharing Star",
    description: "Shared 10 items with the community",
    icon: "⭐",
    iconComponent: "Star",
    color: "from-blue-500 to-cyan-600",
    backgroundColor: "bg-blue-100",
    textColor: "text-blue-800",
    level: "silver",
    rarity: "rare",
    points: 500,
    requirementType: "items_shared",
    requirementValue: 10,
    category: "sharing",
  },
  {
    name: "Sharing Legend",
    description: "Shared 50 items with the community",
    icon: "🌟",
    iconComponent: "Sparkles",
    color: "from-purple-500 to-pink-600",
    backgroundColor: "bg-purple-100",
    textColor: "text-purple-800",
    level: "gold",
    rarity: "epic",
    points: 1000,
    requirementType: "items_shared",
    requirementValue: 50,
    category: "sharing",
  },

  // Community Badges
  {
    name: "Community Helper",
    description: "Completed 5 successful exchanges",
    icon: "🤝",
    iconComponent: "Handshake",
    color: "from-teal-500 to-emerald-600",
    backgroundColor: "bg-teal-100",
    textColor: "text-teal-800",
    level: "bronze",
    rarity: "common",
    points: 200,
    requirementType: "exchanges_completed",
    requirementValue: 5,
    category: "community",
  },
  {
    name: "Community Hero",
    description: "Completed 20 successful exchanges",
    icon: "🦸",
    iconComponent: "Users",
    color: "from-orange-500 to-red-600",
    backgroundColor: "bg-orange-100",
    textColor: "text-orange-800",
    level: "silver",
    rarity: "rare",
    points: 500,
    requirementType: "exchanges_completed",
    requirementValue: 20,
    category: "community",
  },
  {
    name: "Community Champion",
    description: "Completed 100 successful exchanges",
    icon: "🏆",
    iconComponent: "Trophy",
    color: "from-yellow-500 to-amber-600",
    backgroundColor: "bg-yellow-100",
    textColor: "text-yellow-800",
    level: "diamond",
    rarity: "legendary",
    points: 2000,
    requirementType: "exchanges_completed",
    requirementValue: 100,
    category: "community",
  },

  // Trust Badges
  {
    name: "Trusted Member",
    description: "Achieved 50+ trust score",
    icon: "🛡️",
    iconComponent: "Shield",
    color: "from-indigo-500 to-blue-600",
    backgroundColor: "bg-indigo-100",
    textColor: "text-indigo-800",
    level: "silver",
    rarity: "rare",
    points: 300,
    requirementType: "trust_score",
    requirementValue: 50,
    category: "achievement",
  },
  {
    name: "Highly Trusted",
    description: "Achieved 80+ trust score",
    icon: "🔒",
    iconComponent: "Lock",
    color: "from-purple-500 to-indigo-600",
    backgroundColor: "bg-purple-100",
    textColor: "text-purple-800",
    level: "gold",
    rarity: "epic",
    points: 500,
    requirementType: "trust_score",
    requirementValue: 80,
    category: "achievement",
  },
  {
    name: "Trusted Legend",
    description: "Achieved 95+ trust score",
    icon: "👑",
    iconComponent: "Crown",
    color: "from-yellow-500 to-orange-600",
    backgroundColor: "bg-yellow-100",
    textColor: "text-yellow-800",
    level: "diamond",
    rarity: "legendary",
    points: 1000,
    requirementType: "trust_score",
    requirementValue: 95,
    category: "achievement",
  },

  // Eco Badges
  {
    name: "Eco Warrior",
    description: "Saved 50kg of CO2 emissions",
    icon: "🌱",
    iconComponent: "Leaf",
    color: "from-green-500 to-emerald-600",
    backgroundColor: "bg-green-100",
    textColor: "text-green-800",
    level: "bronze",
    rarity: "rare",
    points: 200,
    requirementType: "carbon_saved",
    requirementValue: 50,
    category: "achievement",
  },
  {
    name: "Eco Hero",
    description: "Saved 200kg of CO2 emissions",
    icon: "🌍",
    iconComponent: "Globe",
    color: "from-blue-500 to-green-600",
    backgroundColor: "bg-blue-100",
    textColor: "text-blue-800",
    level: "gold",
    rarity: "epic",
    points: 500,
    requirementType: "carbon_saved",
    requirementValue: 200,
    category: "achievement",
  },

  // Points Badges
  {
    name: "Point Collector",
    description: "Earned 1000 points",
    icon: "💰",
    iconComponent: "Coins",
    color: "from-yellow-500 to-amber-600",
    backgroundColor: "bg-yellow-100",
    textColor: "text-yellow-800",
    level: "bronze",
    rarity: "common",
    points: 100,
    requirementType: "points",
    requirementValue: 1000,
    category: "achievement",
  },
  {
    name: "Point Master",
    description: "Earned 5000 points",
    icon: "💎",
    iconComponent: "Gem",
    color: "from-purple-500 to-pink-600",
    backgroundColor: "bg-purple-100",
    textColor: "text-purple-800",
    level: "gold",
    rarity: "epic",
    points: 500,
    requirementType: "points",
    requirementValue: 5000,
    category: "achievement",
  },

  // Verification Badges
  {
    name: "Verified Member",
    description: "Email verified",
    icon: "✅",
    iconComponent: "CheckCircle",
    color: "from-green-500 to-emerald-600",
    backgroundColor: "bg-green-100",
    textColor: "text-green-800",
    level: "bronze",
    rarity: "common",
    points: 50,
    requirementType: "verification_status",
    requirementValue: 1,
    category: "verification",
  },
  {
    name: "ID Verified",
    description: "Government ID verified",
    icon: "🪪",
    iconComponent: "IdCard",
    color: "from-blue-500 to-cyan-600",
    backgroundColor: "bg-blue-100",
    textColor: "text-blue-800",
    level: "silver",
    rarity: "rare",
    points: 100,
    requirementType: "verification_status",
    requirementValue: 1,
    category: "verification",
    additionalRequirements: { idVerified: true },
  },

  // Milestone Badges
  {
    name: "1 Year Member",
    description: "Been a member for 1 year",
    icon: "🎂",
    iconComponent: "Cake",
    color: "from-pink-500 to-rose-600",
    backgroundColor: "bg-pink-100",
    textColor: "text-pink-800",
    level: "silver",
    rarity: "rare",
    points: 200,
    requirementType: "years_member",
    requirementValue: 1,
    category: "milestone",
  },
  {
    name: "3 Year Member",
    description: "Been a member for 3 years",
    icon: "🎉",
    iconComponent: "Party",
    color: "from-purple-500 to-indigo-600",
    backgroundColor: "bg-purple-100",
    textColor: "text-purple-800",
    level: "gold",
    rarity: "epic",
    points: 500,
    requirementType: "years_member",
    requirementValue: 3,
    category: "milestone",
  },
];

async function seedBadges() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");

    // Clear existing badges
    await Badge.deleteMany({});
    console.log("Cleared existing badges");

    // Insert new badges
    await Badge.insertMany(badges);
    console.log(`✅ Seeded ${badges.length} badges`);

    process.exit(0);
  } catch (error) {
    console.error("Error seeding badges:", error);
    process.exit(1);
  }
}

seedBadges();
